const initialVerbs = [
  {
    id: 'v1',
    verb: 'wake up',
    translation: 'прокидатися',
    topicId: 't1',
    status: 'mastered',
    example: 'I usually wake up at 7 AM every day.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v2',
    verb: 'put on',
    translation: 'надягати (одяг)',
    topicId: 't1',
    status: 'mastered',
    example: 'She put on her heavy winter coat.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v3',
    verb: 'look for',
    translation: 'шукати щось або когось',
    topicId: 't1',
    status: 'new',
    example: 'I am looking for my keys. Have you seen them?',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v4',
    verb: 'give up',
    translation: 'здаватися, кидати (звичку)',
    topicId: 't1',
    status: 'new',
    example: 'Never give up on your dreams.',
    lastReviewed: '2026-05-18T11:37:18.396Z',
    repetitions: 2,
  },
  {
    id: 'v5',
    verb: 'go out',
    translation: 'виходити гуляти, проводити час поза домом',
    topicId: 't1',
    status: 'new',
    example: "Let's go out for dinner tonight.",
    lastReviewed: '2026-05-18T11:37:45.474Z',
    repetitions: 1,
  },
  {
    id: 'v6',
    verb: 'carry out',
    translation: 'виконувати, проводити (план, дослідження)',
    topicId: 't2',
    status: 'hard',
    example: 'The team will carry out the project plan next week.',
    lastReviewed: '2026-05-18T12:47:12.828Z',
    repetitions: 3,
  },
  {
    id: 'v7',
    verb: 'call off',
    translation: 'скасовувати (зустріч, подію)',
    topicId: 't2',
    status: 'hard',
    example: 'They had to call off the meeting due to the weather.',
    lastReviewed: '2026-05-18T12:47:02.124Z',
    repetitions: 3,
  },
  {
    id: 'v8',
    verb: 'set up',
    translation: 'засновувати, створювати (бізнес, систему)',
    topicId: 't2',
    status: 'new',
    example: 'He decided to set up his own software development company.',
    lastReviewed: '2026-05-18T12:46:32.364Z',
    repetitions: 2,
  },
  {
    id: 'v9',
    verb: 'put off',
    translation: 'відкладати на потім, переносити',
    topicId: 't2',
    status: 'hard',
    example: 'Never put off until tomorrow what you can do today.',
    lastReviewed: '2026-05-18T12:47:07.020Z',
    repetitions: 2,
  },
  {
    id: 'v10',
    verb: 'fill out',
    translation: 'заповнювати (анкету, бланк)',
    topicId: 't2',
    status: 'hard',
    example: 'Please fill out this registration form.',
    lastReviewed: '2026-05-18T12:46:56.208Z',
    repetitions: 2,
  },
  {
    id: 'v11',
    verb: 'check in',
    translation: 'реєструватися (в готелі, аеропорту)',
    topicId: 't3',
    status: 'mastered',
    example: 'We must check in at least two hours before the flight.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v12',
    verb: 'get in / into',
    translation: 'сідати у машину / заходити у приміщення',
    topicId: 't3',
    status: 'new',
    example: 'Get into the car, we are running late!',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v13',
    verb: 'get off',
    translation: 'виходити з транспорту (автобус, потяг, літак)',
    topicId: 't3',
    status: 'hard',
    example: 'I need to get off at the next bus stop.',
    lastReviewed: '2026-05-18T11:37:40.796Z',
    repetitions: 1,
  },
  {
    id: 'v14',
    verb: 'look around',
    translation: 'озиратися, оглядати місцевість',
    topicId: 't3',
    status: 'new',
    example: 'We spent the afternoon looking around the old town.',
    lastReviewed: '2026-05-18T11:37:14.872Z',
    repetitions: 1,
  },
  {
    id: 'v15',
    verb: 'set off',
    translation: 'вирушати в дорогу, починати подорож',
    topicId: 't3',
    status: 'hard',
    example: 'They set off early in the morning to avoid traffic.',
    lastReviewed: '2026-05-18T11:37:55.015Z',
    repetitions: 2,
  },
  {
    id: 'v_1779103979563',
    verb: 'take on',
    translation: 'взяти на себе роботу / відповідальність',
    topicId: 't2',
    example: 'She took on a new project last month.',
    status: 'new',
    repetitions: 1,
    lastReviewed: '2026-05-18T12:46:45.988Z',
  },
  {
    id: 'v_1779104113046',
    verb: 'move up',
    translation: 'просуватись кар’єрно',
    topicId: 't2',
    example: 'He moved up to a management position.',
    status: 'new',
    repetitions: 1,
    lastReviewed: '2026-05-18T12:47:16.580Z',
  },
  {
    id: 'v_1779105680042',
    verb: 'deal with',
    translation: 'мати справу з чимось / вирішувати проблему',
    topicId: 't2',
    example: 'I deal with customer complaints.',
    status: 'new',
    repetitions: 1,
    lastReviewed: '2026-05-18T12:46:36.888Z',
  },
  {
    id: 'v_1779105708225',
    verb: 'come up with',
    translation: 'придумати ідею / рішення',
    topicId: 't2',
    example: 'We need to come up with a better strategy.',
    status: 'hard',
    repetitions: 1,
    lastReviewed: '2026-05-18T12:46:41.676Z',
  },
  {
    id: 'v_1779105740065',
    verb: 'fall behind',
    translation: 'відставати',
    topicId: 't2',
    example: 'The project fell behind schedule.',
    status: 'new',
    repetitions: 1,
    lastReviewed: '2026-05-18T12:46:50.020Z',
  },
  {
    id: 'v21',
    verb: 'get up',
    translation: 'вставати (з ліжка)',
    topicId: 't1',
    status: 'new',
    example: 'I usually get up at 7 AM.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v22',
    verb: 'clean up',
    translation: 'прибирати',
    topicId: 't1',
    status: 'new',
    example: 'We need to clean up the kitchen.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v23',
    verb: 'wash up',
    translation: 'мити посуд',
    topicId: 't1',
    status: 'new',
    example: 'He helped to wash up after dinner.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v24',
    verb: 'turn on',
    translation: 'вмикати (світло, прилад)',
    topicId: 't1',
    status: 'new',
    example: 'Can you turn on the light?',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v25',
    verb: 'turn off',
    translation: 'вимикати (світло, прилад)',
    topicId: 't1',
    status: 'new',
    example: "Don't forget to turn off the TV.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v26',
    verb: 'throw away',
    translation: 'викидати',
    topicId: 't1',
    status: 'new',
    example: "Don't throw away that old magazine.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v27',
    verb: 'pick up',
    translation: 'піднімати, підбирати',
    topicId: 't1',
    status: 'new',
    example: 'Can you pick up the kids from school?',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v28',
    verb: 'hang up',
    translation: 'вішати (одяг), класти слухавку',
    topicId: 't1',
    status: 'new',
    example: 'Please hang up your coat in the closet.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v29',
    verb: 'grow up',
    translation: 'рости, дорослішати',
    topicId: 't1',
    status: 'new',
    example: 'He grew up in a small town.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v30',
    verb: 'dress up',
    translation: 'наряджатися, вишукано одягатися',
    topicId: 't1',
    status: 'new',
    example: "You don't need to dress up for the party.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v31',
    verb: 'take off',
    translation: 'знімати (одяг)',
    topicId: 't1',
    status: 'new',
    example: 'Please take off your shoes at the door.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v32',
    verb: 'bring up',
    translation: 'виховувати (дітей)',
    topicId: 't1',
    status: 'new',
    example: 'She brought up three children on her own.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v33',
    verb: 'look after',
    translation: 'доглядати за кимось',
    topicId: 't1',
    status: 'new',
    example: 'Who will look after the cat while we are away?',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v34',
    verb: 'run out of',
    translation: 'закінчуватися (про продукти, час)',
    topicId: 't1',
    status: 'new',
    example: 'We have run out of milk.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v35',
    verb: 'stay up',
    translation: 'не лягати спати, не спати допізна',
    topicId: 't1',
    status: 'new',
    example: 'The kids wanted to stay up late.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v36',
    verb: 'lie down',
    translation: 'прилягти',
    topicId: 't1',
    status: 'new',
    example: "I'm going to lie down for a few minutes.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v37',
    verb: 'lock up',
    translation: 'замикати (будинок)',
    topicId: 't1',
    status: 'new',
    example: 'Make sure you lock up before leaving.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v38',
    verb: 'mess up',
    translation: 'влаштовувати безлад, псувати',
    topicId: 't1',
    status: 'new',
    example: "Don't mess up the living room.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v39',
    verb: 'clear up',
    translation: 'прибирати, прояснюватися (про погоду)',
    topicId: 't1',
    status: 'new',
    example: 'The weather should clear up by tomorrow.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v40',
    verb: 'watch out',
    translation: 'бути обережним',
    topicId: 't1',
    status: 'new',
    example: 'Watch out for the wet floor!',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v41',
    verb: 'look forward to',
    translation: 'з нетерпінням чекати',
    topicId: 't1',
    status: 'new',
    example: 'I look forward to meeting you.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v42',
    verb: 'find out',
    translation: "дізнаватися, з'ясовувати",
    topicId: 't1',
    status: 'new',
    example: 'We need to find out the truth.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v43',
    verb: 'show up',
    translation: "з'являтися, приходити",
    topicId: 't1',
    status: 'new',
    example: "He didn't show up for the meeting.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v44',
    verb: 'try on',
    translation: 'приміряти (одяг)',
    topicId: 't1',
    status: 'new',
    example: 'You should try on this jacket.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v45',
    verb: 'back down',
    translation: 'відступати, визнавати помилку',
    topicId: 't1',
    status: 'new',
    example: 'Neither side was willing to back down.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v46',
    verb: 'hand in',
    translation: 'здавати (звіт, роботу)',
    topicId: 't2',
    status: 'new',
    example: 'You must hand in your essay by Friday.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v47',
    verb: 'take over',
    translation: "переймати (обов'язки, контроль)",
    topicId: 't2',
    status: 'new',
    example: 'The deputy manager will take over next week.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v48',
    verb: 'burn out',
    translation: 'вигоріти (на роботі)',
    topicId: 't2',
    status: 'new',
    example: 'If you work too hard, you will burn out.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v49',
    verb: 'work out',
    translation: 'розробляти, вирішувати (проблему)',
    topicId: 't2',
    status: 'new',
    example: 'We need to work out a solution to this problem.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v50',
    verb: 'back up',
    translation: 'робити резервну копію, підтримувати',
    topicId: 't2',
    status: 'new',
    example: 'Remember to back up your files daily.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v51',
    verb: 'lay off',
    translation: 'звільняти (через скорочення)',
    topicId: 't2',
    status: 'new',
    example: 'The company laid off 50 workers.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v52',
    verb: 'step down',
    translation: 'йти у відставку, залишати посаду',
    topicId: 't2',
    status: 'new',
    example: 'The CEO decided to step down.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v53',
    verb: 'pencil in',
    translation: 'попередньо запланувати',
    topicId: 't2',
    status: 'new',
    example: "Let's pencil in a meeting for Monday.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v54',
    verb: 'sign up',
    translation: 'реєструватися, записуватися',
    topicId: 't2',
    status: 'new',
    example: 'You can sign up for the course online.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v55',
    verb: 'follow up',
    translation: 'продовжувати (дію), відстежувати',
    topicId: 't2',
    status: 'new',
    example: 'I will follow up on your request tomorrow.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v56',
    verb: 'close down',
    translation: 'закриватися (про бізнес)',
    topicId: 't2',
    status: 'new',
    example: 'The factory closed down last year.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v57',
    verb: 'break down',
    translation: 'ламатися, детально розбирати',
    topicId: 't2',
    status: 'new',
    example: 'The negotiation broke down over a small detail.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v58',
    verb: 'catch up',
    translation: 'наздоганяти (пропущене)',
    topicId: 't2',
    status: 'new',
    example: 'I need to catch up on my work.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v59',
    verb: 'speed up',
    translation: 'прискорювати(ся)',
    topicId: 't2',
    status: 'new',
    example: 'We need to speed up the production process.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v60',
    verb: 'slow down',
    translation: 'сповільнювати(ся)',
    topicId: 't2',
    status: 'new',
    example: 'Business slows down during the summer.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v61',
    verb: 'look into',
    translation: 'розслідувати, вивчати питання',
    topicId: 't2',
    status: 'new',
    example: 'The manager promised to look into the matter.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v62',
    verb: 'point out',
    translation: 'вказувати, звертати увагу',
    topicId: 't2',
    status: 'new',
    example: 'He pointed out several mistakes in the report.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v63',
    verb: 'run by',
    translation: 'узгодити з кимось, порадитися',
    topicId: 't2',
    status: 'new',
    example: 'Let me run this idea by you first.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v64',
    verb: 'type up',
    translation: 'передруковувати, оформлювати в електронному вигляді',
    topicId: 't2',
    status: 'new',
    example: 'She typed up the notes from the meeting.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v65',
    verb: 'report to',
    translation: 'підпорядковуватися комусь',
    topicId: 't2',
    status: 'new',
    example: 'You will report directly to the director.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v66',
    verb: 'step up',
    translation: 'активізувати зусилля, брати ініціативу',
    topicId: 't2',
    status: 'new',
    example: 'The team needs to step up its game.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v67',
    verb: 'burn through',
    translation: 'швидко витрачати (гроші, ресурси)',
    topicId: 't2',
    status: 'new',
    example: 'They burned through their budget very quickly.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v68',
    verb: 'cut back',
    translation: 'скорочувати (витрати)',
    topicId: 't2',
    status: 'new',
    example: 'We must cut back on our expenses.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v69',
    verb: 'phase out',
    translation: 'поступово припиняти використання',
    topicId: 't2',
    status: 'new',
    example: 'The old system will be phased out next month.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v70',
    verb: 'take down',
    translation: 'записувати (нотатки)',
    topicId: 't2',
    status: 'new',
    example: 'Please take down everything I say.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v71',
    verb: 'check out',
    translation: 'виписуватися (з готелю)',
    topicId: 't3',
    status: 'new',
    example: 'We checked out of the hotel at noon.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v72',
    verb: 'set out',
    translation: 'вирушати в дорогу',
    topicId: 't3',
    status: 'new',
    example: 'They set out on their journey across Europe.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v73',
    verb: 'drop off',
    translation: 'висаджувати (пасажира), завозити щось',
    topicId: 't3',
    status: 'new',
    example: 'Can you drop me off at the station?',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v74',
    verb: 'see off',
    translation: 'проводжати (когось у дорогу)',
    topicId: 't3',
    status: 'new',
    example: 'My parents came to the airport to see me off.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v75',
    verb: 'hold up',
    translation: 'затримувати (в дорозі)',
    topicId: 't3',
    status: 'new',
    example: "Sorry I'm late, I was held up in traffic.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v76',
    verb: 'pull over',
    translation: 'притиснутися до узбіччя, зупинити авто',
    topicId: 't3',
    status: 'new',
    example: 'The police officer told him to pull over.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v77',
    verb: 'get back',
    translation: 'повертатися (з подорожі)',
    topicId: 't3',
    status: 'new',
    example: 'When did you get back from your holiday?',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v78',
    verb: 'get on',
    translation: 'сідати (в автобус, потяг, літак)',
    topicId: 't3',
    status: 'new',
    example: 'We got on the train just before it left.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v79',
    verb: 'hurry up',
    translation: 'поспішати',
    topicId: 't3',
    status: 'new',
    example: 'Hurry up or we will miss our flight!',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v80',
    verb: 'head for',
    translation: 'прямувати кудись',
    topicId: 't3',
    status: 'new',
    example: 'We are heading for the mountains.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v81',
    verb: 'turn back',
    translation: 'повертатися назад',
    topicId: 't3',
    status: 'new',
    example: 'The weather was so bad we had to turn back.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v82',
    verb: 'stop over',
    translation: 'робити проміжну зупинку',
    topicId: 't3',
    status: 'new',
    example: 'We stopped over in New York for two days.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v83',
    verb: 'move on',
    translation: 'рухатися далі, продовжувати шлях',
    topicId: 't3',
    status: 'new',
    example: "It's time to move on to the next city.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v84',
    verb: 'pack up',
    translation: "збирати речі (для від'їзду)",
    topicId: 't3',
    status: 'new',
    example: 'We packed up our tent and left.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v85',
    verb: 'drive off',
    translation: 'поїхати (на машині)',
    topicId: 't3',
    status: 'new',
    example: 'He got into his car and drove off.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v86',
    verb: 'break through',
    translation: 'прориватися',
    topicId: 't3',
    status: 'new',
    example: 'The sun broke through the clouds.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v87',
    verb: 'pull up',
    translation: 'зупинити автомобіль',
    topicId: 't3',
    status: 'new',
    example: 'A taxi pulled up outside the hotel.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v88',
    verb: 'get away',
    translation: 'вирватися на відпочинок, втекти',
    topicId: 't3',
    status: 'new',
    example: 'We hope to get away for a weekend soon.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v89',
    verb: 'loop around',
    translation: 'зробити петлю, обійти навколо',
    topicId: 't3',
    status: 'new',
    example: 'The road loops around the lake.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v90',
    verb: 'map out',
    translation: 'планувати (маршрут)',
    topicId: 't3',
    status: 'new',
    example: 'They mapped out their road trip on a big map.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v91',
    verb: 'warm up',
    translation: 'розминатися',
    topicId: 't4',
    status: 'new',
    example: 'Always warm up before exercising.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v92',
    verb: 'cool down',
    translation: 'охолоджуватися після тренування',
    topicId: 't4',
    status: 'new',
    example: 'Make sure to cool down after your run.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v93',
    verb: 'pass out',
    translation: 'знепритомніти',
    topicId: 't4',
    status: 'new',
    example: 'It was so hot that she passed out.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v94',
    verb: 'come down with',
    translation: 'злягти з хворобою',
    topicId: 't4',
    status: 'new',
    example: 'I think I am coming down with the flu.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v95',
    verb: 'get over',
    translation: 'одужати від хвороби',
    topicId: 't4',
    status: 'new',
    example: 'It took him a long time to get over his illness.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v96',
    verb: 'fight off',
    translation: 'відбиватися (від інфекції)',
    topicId: 't4',
    status: 'new',
    example: 'Your body is trying to fight off the virus.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v97',
    verb: 'throw up',
    translation: 'нудити, блювати',
    topicId: 't4',
    status: 'new',
    example: 'The smell made him want to throw up.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v98',
    verb: 'build up',
    translation: "зміцнювати (імунітет, м'язи)",
    topicId: 't4',
    status: 'new',
    example: 'You need to build up your stamina.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v99',
    verb: 'cut down on',
    translation: 'зменшити споживання (чогось)',
    topicId: 't4',
    status: 'new',
    example: 'You should cut down on sugar.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v100',
    verb: 'tire out',
    translation: 'виснажувати',
    topicId: 't4',
    status: 'new',
    example: 'The long workout tired him out.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v101',
    verb: 'wear out',
    translation: 'сильно втомлювати, виснажувати',
    topicId: 't4',
    status: 'new',
    example: 'Walking all day wore me out.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v102',
    verb: 'shake off',
    translation: 'позбутися (хвороби, застуди)',
    topicId: 't4',
    status: 'new',
    example: "I can't seem to shake off this cold.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v103',
    verb: 'swell up',
    translation: 'набрякати, пухнути',
    topicId: 't4',
    status: 'new',
    example: 'My ankle started to swell up after the fall.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v104',
    verb: 'join in',
    translation: 'приєднуватися (до гри/діяльності)',
    topicId: 't4',
    status: 'new',
    example: 'We are playing football, do you want to join in?',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v105',
    verb: 'pass away',
    translation: 'померти, піти з життя',
    topicId: 't4',
    status: 'new',
    example: 'His grandfather passed away peacefully.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v106',
    verb: 'come to',
    translation: 'прийти до тями',
    topicId: 't4',
    status: 'new',
    example: 'When she came to, she was in the hospital.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v107',
    verb: 'pull through',
    translation: 'викарабкатися, вижити',
    topicId: 't4',
    status: 'new',
    example: 'The doctor said she will pull through.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v108',
    verb: 'bulk up',
    translation: "набирати м'язову масу",
    topicId: 't4',
    status: 'new',
    example: 'He is eating more protein to bulk up.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v109',
    verb: 'burn off',
    translation: 'спалювати (калорії)',
    topicId: 't4',
    status: 'new',
    example: 'Running helps to burn off calories.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v110',
    verb: 'knock out',
    translation: 'вирубати, нокаутувати',
    topicId: 't4',
    status: 'new',
    example: 'The boxer was knocked out in the third round.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v111',
    verb: 'tone up',
    translation: 'підтягнути тіло, приводити в тонус',
    topicId: 't4',
    status: 'new',
    example: 'This exercise will help tone up your muscles.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v112',
    verb: 'ease up',
    translation: 'вщухати, слабшати (про біль)',
    topicId: 't4',
    status: 'new',
    example: 'The pain began to ease up after an hour.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v113',
    verb: 'get along with',
    translation: 'ладнати (з кимось)',
    topicId: 't5',
    status: 'new',
    example: 'Do you get along with your coworkers?',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v114',
    verb: 'fall out with',
    translation: 'посваритися (з кимось)',
    topicId: 't5',
    status: 'new',
    example: 'She fell out with her best friend over a boy.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v115',
    verb: 'make up',
    translation: 'миритися',
    topicId: 't5',
    status: 'new',
    example: 'They always argue but they make up quickly.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v116',
    verb: 'ask out',
    translation: 'запросити на побачення',
    topicId: 't5',
    status: 'new',
    example: 'He finally gathered the courage to ask her out.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v117',
    verb: 'break up',
    translation: 'розійтися, розірвати стосунки',
    topicId: 't5',
    status: 'new',
    example: 'They decided to break up after three years.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v118',
    verb: 'count on',
    translation: 'розраховувати на когось',
    topicId: 't5',
    status: 'new',
    example: 'You can always count on me for help.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v119',
    verb: 'let down',
    translation: 'підводити, розчаровувати',
    topicId: 't5',
    status: 'new',
    example: "Don't let me down this time.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v120',
    verb: 'run into',
    translation: 'випадково зустріти',
    topicId: 't5',
    status: 'new',
    example: 'I ran into an old friend at the supermarket.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v121',
    verb: 'stick up for',
    translation: 'заступатися (за когось)',
    topicId: 't5',
    status: 'new',
    example: 'Thank you for sticking up for me.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v122',
    verb: 'talk back',
    translation: 'огризатися, зухвало відповідати',
    topicId: 't5',
    status: 'new',
    example: "Children shouldn't talk back to their parents.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v123',
    verb: 'drift apart',
    translation: 'віддалятися (один від одного)',
    topicId: 't5',
    status: 'new',
    example: 'Over the years, the two friends drifted apart.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v124',
    verb: 'look up to',
    translation: 'поважати, брати приклад',
    topicId: 't5',
    status: 'new',
    example: 'He looks up to his older brother.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v125',
    verb: 'look down on',
    translation: 'дивитися зверхньо',
    topicId: 't5',
    status: 'new',
    example: "You shouldn't look down on people who are less fortunate.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v126',
    verb: 'hit it off',
    translation: 'швидко здружитися',
    topicId: 't5',
    status: 'new',
    example: 'They hit it off immediately at the party.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v127',
    verb: 'cheer up',
    translation: 'піднімати настрій, втішати',
    topicId: 't5',
    status: 'new',
    example: 'I brought you some chocolate to cheer you up.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v128',
    verb: 'stand up for',
    translation: 'відстоювати, захищати',
    topicId: 't5',
    status: 'new',
    example: 'You must stand up for your rights.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v129',
    verb: 'open up',
    translation: 'відкриватися (емоційно)',
    topicId: 't5',
    status: 'new',
    example: "It's hard for him to open up to strangers.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v130',
    verb: 'fit in',
    translation: 'вписуватися (в компанію)',
    topicId: 't5',
    status: 'new',
    example: 'She struggled to fit in at her new school.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v131',
    verb: 'break in',
    translation: 'перебивати (розмову)',
    topicId: 't5',
    status: 'new',
    example: "Don't break in while I am speaking.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v132',
    verb: 'tell off',
    translation: 'сварити, робити зауваження',
    topicId: 't5',
    status: 'new',
    example: 'The teacher told him off for being late.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v133',
    verb: 'laugh off',
    translation: 'переводити в жарт',
    topicId: 't5',
    status: 'new',
    example: 'She managed to laugh off the embarrassing moment.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v134',
    verb: 'cut off',
    translation: 'переривати (співрозмовника)',
    topicId: 't5',
    status: 'new',
    example: 'He cut me off in the middle of a sentence.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v135',
    verb: 'catch on',
    translation: 'розуміти, схоплювати на льоту',
    topicId: 't6',
    status: 'new',
    example: 'He is smart and catches on quickly.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v136',
    verb: 'look up',
    translation: 'шукати (в словнику чи інтернеті)',
    topicId: 't6',
    status: 'new',
    example: "If you don't know the word, look it up.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v137',
    verb: 'read up on',
    translation: 'детально вивчати (тему)',
    topicId: 't6',
    status: 'new',
    example: 'I need to read up on the history of this country.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v138',
    verb: 'drop out',
    translation: 'кидати навчання',
    topicId: 't6',
    status: 'new',
    example: 'He dropped out of university to start a business.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v139',
    verb: 'keep up with',
    translation: 'встигати за (матеріалом, прогресом)',
    topicId: 't6',
    status: 'new',
    example: "It's hard to keep up with the latest technology.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v140',
    verb: 'copy out',
    translation: 'переписувати',
    topicId: 't6',
    status: 'new',
    example: 'Copy out the text into your notebooks.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v141',
    verb: 'sum up',
    translation: 'підсумовувати',
    topicId: 't6',
    status: 'new',
    example: 'To sum up, we need more time.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v142',
    verb: 'hand out',
    translation: 'роздавати (матеріали)',
    topicId: 't6',
    status: 'new',
    example: 'The teacher will hand out the exam papers.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v143',
    verb: 'pore over',
    translation: 'ретельно вивчати, сидіти над книжками',
    topicId: 't6',
    status: 'new',
    example: 'She spent hours poring over the documents.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v144',
    verb: 'think over',
    translation: 'обмірковувати',
    topicId: 't6',
    status: 'new',
    example: 'Take some time to think over my offer.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v145',
    verb: 'figure out',
    translation: 'розібратися, зрозуміти',
    topicId: 't6',
    status: 'new',
    example: "I can't figure out how to use this app.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v146',
    verb: 'cross out',
    translation: 'закреслювати',
    topicId: 't6',
    status: 'new',
    example: 'If you make a mistake, just cross it out.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v147',
    verb: 'block out',
    translation: 'ігнорувати, абстрагуватися',
    topicId: 't6',
    status: 'new',
    example: 'Try to block out all the noise.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v148',
    verb: 'jot down',
    translation: 'коротко занотовувати',
    topicId: 't6',
    status: 'new',
    example: 'Let me jot down your phone number.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v149',
    verb: 'pass down',
    translation: 'передавати (знання, традиції)',
    topicId: 't6',
    status: 'new',
    example: 'The story was passed down through generations.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v150',
    verb: 'puzzle out',
    translation: 'розгадати, розібратися',
    topicId: 't6',
    status: 'new',
    example: 'We managed to puzzle out the riddle.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v151',
    verb: 'sketch out',
    translation: 'накидати план, зробити ескіз',
    topicId: 't6',
    status: 'new',
    example: 'He sketched out his plan on a napkin.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v152',
    verb: 'write down',
    translation: 'записувати, занотовувати',
    topicId: 't6',
    status: 'new',
    example: 'Please write down your name here.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v153',
    verb: 'speak up',
    translation: 'говорити голосніше',
    topicId: 't6',
    status: 'new',
    example: 'Could you speak up a bit, please?',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v154',
    verb: 'turn over',
    translation: 'перегортати (сторінку)',
    topicId: 't6',
    status: 'new',
    example: 'Turn over the page to find the answer.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v155',
    verb: 'read out',
    translation: 'читати вголос',
    topicId: 't6',
    status: 'new',
    example: 'Please read out the instructions.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v156',
    verb: 'look through',
    translation: 'переглядати (матеріал)',
    topicId: 't6',
    status: 'new',
    example: 'I need to look through my notes before the test.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v157',
    verb: 'save up',
    translation: 'збирати, заощаджувати (гроші)',
    topicId: 't7',
    status: 'new',
    example: 'She is saving up for a new laptop.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v158',
    verb: 'pay back',
    translation: 'повертати (борг)',
    topicId: 't7',
    status: 'new',
    example: 'I will pay you back tomorrow.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v159',
    verb: 'rip off',
    translation: 'обдирати, продавати втридорога',
    topicId: 't7',
    status: 'new',
    example: 'Tourists are often ripped off in this area.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v160',
    verb: 'splash out',
    translation: 'смітити грошима, витрачатися',
    topicId: 't7',
    status: 'new',
    example: 'They splashed out on a luxury vacation.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v161',
    verb: 'shop around',
    translation: 'порівнювати ціни, шукати вигоду',
    topicId: 't7',
    status: 'new',
    example: "It's wise to shop around before buying a car.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v162',
    verb: 'pay off',
    translation: 'полністю виплатити (борг, кредит)',
    topicId: 't7',
    status: 'new',
    example: 'It took me five years to pay off the loan.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v163',
    verb: 'run up',
    translation: 'накопичувати (борги, рахунки)',
    topicId: 't7',
    status: 'new',
    example: 'He ran up a huge bill at the hotel.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v164',
    verb: 'put down',
    translation: 'давати завдаток, перший внесок',
    topicId: 't7',
    status: 'new',
    example: 'We put down a deposit on the house.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v165',
    verb: 'sell out',
    translation: 'розпродати повністю',
    topicId: 't7',
    status: 'new',
    example: 'The concert tickets sold out in minutes.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v166',
    verb: 'fork out',
    translation: 'розщедритися, неохоче платити',
    topicId: 't7',
    status: 'new',
    example: 'I had to fork out a lot of money for car repairs.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v167',
    verb: 'chip in',
    translation: 'скидатися (грошима)',
    topicId: 't7',
    status: 'new',
    example: 'Everyone chipped in to buy a gift.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v168',
    verb: 'live on',
    translation: 'жити на (певну суму)',
    topicId: 't7',
    status: 'new',
    example: "It's difficult to live on such a small salary.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v169',
    verb: 'knock off',
    translation: 'знижувати ціну, робити знижку',
    topicId: 't7',
    status: 'new',
    example: 'They knocked off 10% from the price.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v170',
    verb: 'add up',
    translation: 'підраховувати, додавати',
    topicId: 't7',
    status: 'new',
    example: "The numbers don't add up correctly.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v171',
    verb: 'bring down',
    translation: 'знижувати (ціни)',
    topicId: 't7',
    status: 'new',
    example: 'The store brought down the prices for Black Friday.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v172',
    verb: 'go up',
    translation: 'рости (про ціни)',
    topicId: 't7',
    status: 'new',
    example: 'The price of oil is going up again.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v173',
    verb: 'pay up',
    translation: 'розплатитися повністю, погасити борг',
    topicId: 't7',
    status: 'new',
    example: 'The debtor finally paid up.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v174',
    verb: 'pay in',
    translation: 'вносити гроші на рахунок',
    topicId: 't7',
    status: 'new',
    example: 'I need to pay some cash into my bank account.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v175',
    verb: 'give away',
    translation: 'роздавати безкоштовно',
    topicId: 't7',
    status: 'new',
    example: 'The shop is giving away free samples.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v176',
    verb: 'buy out',
    translation: 'викуповувати (частку, компанію)',
    topicId: 't7',
    status: 'new',
    example: 'The tech giant decided to buy out the startup.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v177',
    verb: 'snap up',
    translation: 'розхоплювати (товари)',
    topicId: 't7',
    status: 'new',
    example: 'Customers snapped up the discounted goods.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v178',
    verb: 'clear out',
    translation: 'розпродавати (залишки товарів)',
    topicId: 't7',
    status: 'new',
    example: 'They are clearing out old stock to make room for new items.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v179',
    verb: 'calm down',
    translation: 'заспокоюватися',
    topicId: 't8',
    status: 'new',
    example: 'Please calm down and tell me what happened.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v180',
    verb: 'flare up',
    translation: 'спалахнути (про гнів)',
    topicId: 't8',
    status: 'new',
    example: 'His temper tended to flare up unexpectedly.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v181',
    verb: 'freak out',
    translation: 'панікувати, зриватися від страху',
    topicId: 't8',
    status: 'new',
    example: "Don't freak out, everything will be fine.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v182',
    verb: 'liven up',
    translation: 'оживляти, робити веселішим',
    topicId: 't8',
    status: 'new',
    example: 'A bit of music will liven up the party.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v183',
    verb: 'bottle up',
    translation: 'приховувати, стримувати (емоції)',
    topicId: 't8',
    status: 'new',
    example: "It's unhealthy to bottle up your feelings.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v184',
    verb: 'lash out',
    translation: 'накидатися на когось з гнівом',
    topicId: 't8',
    status: 'new',
    example: 'He lashed out at his sister when he was angry.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v185',
    verb: 'blow up',
    translation: 'вибухнути від гніву',
    topicId: 't8',
    status: 'new',
    example: 'He blew up at the waiter for making a mistake.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v186',
    verb: 'choke up',
    translation: 'задихатися від сліз або емоцій',
    topicId: 't8',
    status: 'new',
    example: 'She choked up when she started talking about her dog.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v187',
    verb: 'crack up',
    translation: 'сильно розсміятися, реготати',
    topicId: 't8',
    status: 'new',
    example: 'His jokes always make me crack up.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v188',
    verb: 'act up',
    translation: 'вередувати, погано поводитися',
    topicId: 't8',
    status: 'new',
    example: 'The kids always act up when they are tired.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v189',
    verb: 'goof around',
    translation: 'валяти дурня',
    topicId: 't8',
    status: 'new',
    example: 'Stop goofing around and do your homework.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v190',
    verb: 'chill out',
    translation: 'розслаблятися, відпочивати',
    topicId: 't8',
    status: 'new',
    example: "Let's just chill out at home tonight.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v191',
    verb: 'wind up',
    translation: 'накручувати себе, хвилюватися',
    topicId: 't8',
    status: 'new',
    example: "Don't wind yourself up over things you can't control.",
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v192',
    verb: 'tear up',
    translation: 'просльозитися, наповнюватися сльозами',
    topicId: 't8',
    status: 'new',
    example: 'She tore up when she read the emotional letter.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v193',
    verb: 'psych up',
    translation: 'психологічно налаштовуватися',
    topicId: 't8',
    status: 'new',
    example: 'I need to psych myself up before the presentation.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v194',
    verb: 'snap out of',
    translation: 'швидко вийти (зі стану туги, трансу)',
    topicId: 't8',
    status: 'new',
    example: 'You need to snap out of this bad mood.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v195',
    verb: 'ease off',
    translation: 'ставати спокійнішим, вщухати',
    topicId: 't8',
    status: 'new',
    example: 'The tension began to ease off after the meeting.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v196',
    verb: 'brighten up',
    translation: 'ставати радіснішим, покращувати настрій',
    topicId: 't8',
    status: 'new',
    example: 'Her smile brightened up my day.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v197',
    verb: 'face up to',
    translation: 'сміливо приймати, дивитися в очі (правді)',
    topicId: 't8',
    status: 'new',
    example: 'You have to face up to reality.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v198',
    verb: 'melt down',
    translation: 'мати нервовий зрив, зриватися',
    topicId: 't8',
    status: 'new',
    example: 'The toddler had a total meltdown in the store.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v199',
    verb: 'freeze up',
    translation: 'заціпеніти від страху або хвилювання',
    topicId: 't8',
    status: 'new',
    example: 'He froze up when the camera started rolling.',
    lastReviewed: null,
    repetitions: 1,
  },
  {
    id: 'v200',
    verb: 'pull together',
    translation: 'зібратися з силами, опанувати себе',
    topicId: 't8',
    status: 'new',
    example: 'We need to pull together to finish this project on time.',
    lastReviewed: null,
    repetitions: 1,
  },
];

export default initialVerbs;